### ISSUE TITLE
Undefined mixin 'form-inline'.

### ISSUE THREAD

**Issue by Aetherus** [anjlab/bootstrap-rails#46]
I installed this gem according to the instruction, then performed `rake assets:precompile`, and got the error "File to import not found or unreadable: input-groups.". I manually added an empty file with this name, and met this issue.

**Comment by yury** [comment]
should work now if you install it from git

**Comment by rudf0rd** [comment]
This problem still exists if you include just portions of bootstrap rather than the entire file.

Example:

```
@import "twitter/bootstrap/_navs";
@import "twitter/bootstrap/_navbar";
```

vs

```
@import "twitter/bootstrap";
```

**Comment by yury** [comment]
_navbar [uses mixing](https://github.com/anjlab/bootstrap-rails/blob/3.0.0/app/assets/stylesheets/twitter/bootstrap/_navbar.scss#L149)  from [_input_groups.scss](https://github.com/anjlab/bootstrap-rails/blob/3.0.0/app/assets/stylesheets/twitter/bootstrap/_input-groups.scss#L120)

also you need `_variables` and `_mixins` files

better way is to create copy of [_app_bootstrap.css.scss](https://gist.github.com/yury/6125678) import it in your application.css.scss and comment out unnecessary imports and test.

**Comment by rudf0rd** [comment]
My mistake.  That was just a snippet of my entire file.

I did do what you had suggested and have everything, then paired down.  Here's the entire list of my imports which still fails with the inline-form error above.  Also, I get this error in dev mode throwing a Sass::SyntaxError, not in doing a precompile.

```
// Core variables and mixins
@import "twitter/bootstrap/_variables";
@import "twitter/bootstrap/_mixins";

// Reset
@import "twitter/bootstrap/_normalize";
@import "twitter/bootstrap/_print";

// Core CSS
@import "twitter/bootstrap/_scaffolding";
@import "twitter/bootstrap/_type";
@import "twitter/bootstrap/_code";
@import "twitter/bootstrap/_grid";

//@import "twitter/bootstrap/_tables";
@import "twitter/bootstrap/_forms";
@import "twitter/bootstrap/_buttons";

// Components: common
@import "twitter/bootstrap/_component-animations";
@import "twitter/bootstrap/_dropdowns";
@import "twitter/bootstrap/_list-group";
@import "twitter/bootstrap/_panels";
@import "twitter/bootstrap/_wells";
@import "twitter/bootstrap/_close";

// Components: Nav
@import "twitter/bootstrap/_navs";
@import "twitter/bootstrap/_navbar";
@import "twitter/bootstrap/_button-groups";
//@import "twitter/bootstrap/_breadcrumbs";
//@import "twitter/bootstrap/_pagination";
//@import "twitter/bootstrap/_pager";

// Components: Popovers
//@import "twitter/bootstrap/_modals";
@import "twitter/bootstrap/_tooltip";
@import "twitter/bootstrap/_popovers";

// Components: Misc
@import "twitter/bootstrap/_alerts";
//@import "twitter/bootstrap/_thumbnails";
//@import "twitter/bootstrap/_media";
//@import "twitter/bootstrap/_labels";
//@import "twitter/bootstrap/_badges";
//@import "twitter/bootstrap/_progress-bars";
//@import "twitter/bootstrap/_accordion";
@import "twitter/bootstrap/_carousel";
@import "twitter/bootstrap/_jumbotron";

// Utility classes
@import "twitter/bootstrap/_utilities"; // Has to be last to override when necessary
//@import "twitter/bootstrap/_responsive-utilities";
```

**Comment by yury** [comment]
yep, that outdated one.
you are missing this line https://gist.github.com/yury/6125678#file-_app_bootstrap-css-scss-L31

Just to be sure, add gem with git like in [read me](https://github.com/anjlab/bootstrap-rails#rails--31) and run `bundle update anjlab-bootstrap-rails`, run `rm -rf tmp/cache` from your app folder and restart server. that should help.

**Comment by rudf0rd** [comment]
Ah perfect.  Thanks Yury.
